version: "3"
services:
  Roboflow-GPU-1:
    image: roboflow/inference-server:cpu
    restart: always
    volumes:
      - shared-volume:/cache

  Roboflow-GPU-2:
    image: roboflow/inference-server:cpu
    restart: always
    volumes:
      - shared-volume:/cache
  Roboflow-GPU-3:
    image: roboflow/inference-server:cpu
    restart: always
    volumes:
      - shared-volume:/cache

  Roboflow-GPU-4:
    image: roboflow/inference-server:cpu
    restart: always
    volumes:
      - shared-volume:/cache
  Load-Balancer:
    image: lb
    restart: always
    ports:
      - 9001:80

volumes:
  shared-volume:
